//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.tasks = new HashSet<task>();
            this.employees = new HashSet<employee>();
        }
    
        public System.Guid project_id { get; set; }
        public string project_name { get; set; }
        public Nullable<System.Guid> project_manager { get; set; }
        public Nullable<System.Guid> client_id { get; set; }
    
        public  client client { get; set; }
        public  employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<task> tasks { get; set; }
        public ICollection<employee> employees { get; set; }
    }
}
