//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public System.Guid task_id { get; set; }
        public System.Guid employee_id { get; set; }
        public System.Guid project_id { get; set; }
        public string task_name { get; set; }
        public Nullable<int> importance_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public Nullable<int> time { get; set; }
        public string detail { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual importance importance { get; set; }
        public virtual project project { get; set; }
        public virtual status status { get; set; }
    }
}
